import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AuthenticatorWrapper from "./AuthenticatorWrapper";
import "@aws-amplify/ui-react/styles.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { UserProvider } from "@/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>  
        <AuthenticatorWrapper>
          <UserProvider>
            <SidebarProvider defaultOpen={true}>
              <AppSidebar/>
              <main className="w-full p-4">
                <SidebarTrigger/>
                {children}
              </main>
            </SidebarProvider>
          </UserProvider>
        </AuthenticatorWrapper>
      </body>
    </html>
  );
}
